### ISSUE TITLE
Stops working in Electron as of v5.0.0

### ISSUE THREAD

**Issue by tribou** [qubyte/fetch-ponyfill#112]
Hi!

I'm trying to share code across a web app and Electron, and it's been working great on `v4`. However, when I try to upgrade this package in the Electron app from `v4.1.0` to `v5.0.0` (or later), all of the network calls silently stop working. v5 appears to still work in the web app with the exact same API code.

Has anyone else gotten version `v5.0.0` or later to work with Electron?

**Comment by qubyte** [comment]
The one thing which I suspect is making an issue for you is this line:

https://github.com/qubyte/fetch-ponyfill/compare/v4.1.0...master#diff-178b8b1d7ee796d6895c2e7e56f77ebbR37

However, this library is tested against webpack:

https://github.com/qubyte/fetch-ponyfill/blob/master/package.json#L15-L16

A reduction would be helpful to determine where this issue is coming from.

**Comment by tribou** [comment]
Ah, I thought that was the culprit as well until yesterday when I noticed that `v5.0.1` wasn't working either even though it has the [previous version of that logic here](https://github.com/qubyte/fetch-ponyfill/blob/3ed5da4a8e042a1a9d47162c40c64e07d45ab192/fetch-browser.js#L37). So now I'm wondering if it is somehow the upgrade to `node-fetch@v2.0.0`...even though that doesn't make as much sense as the line you referenced.

Let me see if I can get a couple example branches up to compare. Unfortunately, it's a pretty large app at the moment. Also, I believe it's still on webpack v3 if that helps at all.

**Comment by tribou** [comment]
After "unmasking" my API helpers, I was able to log the error:

![image](https://user-images.githubusercontent.com/1641390/40660888-ec51d866-6317-11e8-9dd1-fc264a9cb9d7.png)

And this is [`fetch-node.js:15`](https://github.com/qubyte/fetch-ponyfill/blob/v5.0.1/fetch-node.js#L15).

Any thoughts?

**Comment by qubyte** [comment]
It's not possible to know what's going on without a little more information. Is this running in Node or in a BrowserWindow. I don't know much about electron, but I suspect you want the browser half of fetch ponyfill rather than the Node half. Try using `require('fetch-ponyfill/build/fetch-browser.js')` and see if you get any further with that.

If that doesn't work for you, then a modern enough electron (which would still be quite old) will support genuine fetch out of the box. If you're fetching in Node, then this module delegates to fetch-node anyway, which might be a better option for you.

**Comment by qubyte** [comment]
This may also be pertinent: https://github.com/electron/electron/issues/1574

**Comment by qubyte** [comment]
@tribou How did you get on?

**Comment by tribou** [comment]
My apologies, I didn't make much more progress. I've still got `v4.1.0` pinned for now until I can find time to debug more.

**Comment by d-fischer** [comment]
This seems to still be an issue.

Also, we can now break compat with 4.1.0 in order to fix this, since 6.x is currently the oldest supported version of Electron.
